export const DRAGITEMSELECTORPREFIX = 'ct-drag-item';
export const RESIZEITEMSELECTORPREFIX = 'ct-resizeable-item';
export const SELECTABLEITEMSELECTORPREFIX = 'ct-selectable-item';

export const DRITEMSELECTORPREFIX = [
  DRAGITEMSELECTORPREFIX,
  RESIZEITEMSELECTORPREFIX,
];

export const DRSITEMSELECTORPREFIX = [
  DRAGITEMSELECTORPREFIX,
  RESIZEITEMSELECTORPREFIX,
  SELECTABLEITEMSELECTORPREFIX,
];

export const DRAGSELECTORPREFIX = 'ct-drag';
export const RESIZEABLESELECTORPREFIX = 'ct-resizeable';
export const SELECTABLESELECTORPREFIX = 'ct-selectable';
export const DROPPABLESELECTORPREFIX = 'ct-droppable';

export const DRSSELECTORPREFIX = [
  DRAGSELECTORPREFIX,
  RESIZEABLESELECTORPREFIX,
  SELECTABLESELECTORPREFIX,
];

// 键盘默认移动的步进
export const KEYBOARD_NORMAL_STEP = 1;

// 键盘快速移动的步进
export const KEYBOARD_FAST_STEP = 10;

// 粘贴X的位置步进
export const PAST_XPOSITION_STEP = 10;

// 粘贴Y的位置步进
export const PAST_YPOSITION_STEP = 10;

